# ----- task setting config -----

# get env information
env: "sc2"
# get task information
task: "stalker-zealot-medium"
# define train tasks and test tasks
train_tasks: ["2s3z", "2s4z", "3s5z"]
train_tasks_data_quality: {
    "2s3z": "medium",
    "2s4z": "medium",
    "3s5z": "medium",
}

test_tasks: ["2s3z","3m", "5m","10m","5m_vs_6m", "9m_vs_10m"]
test_tasks_data_quality: {
}

# define additional pretrain tasks
pretrain_tasks: ["2s3z", "2s4z", "3s5z"]
pretrain_tasks_data_quality: {
    "2s3z": "medium",
    "2s4z": "medium",
    "3s5z": "medium",
}
